server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/befit
    username: postgres
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret: "NLrtJY4slIon0zXF8Gg9d1eBTMCqKOUw"
  expiration: 3600000